build_mac_arm_task:
  env:
#     COMPILER: clang
    NJOBS: 4
    SIGN_KEY: ENCRYPTED[6e0e770a3b98dbe3a70bf0206a4735f86ea682005868ff785f5a507f12ffe74165057c089d1e49b32b0a1c613e490e01]
    KEY_PASS: ENCRYPTED[fec9deb715cea8d2ab44a3d3a657096a563d1c342425875cfb046d92818f27e859bc4deb5289cf3597beaf2ac5807a67]

  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest

  timeout_in: 60m

  install_script:
    - chmod +x ports/ci/mac-arm/install_deps.sh
    - ./ports/ci/mac-arm/install_deps.sh

  script:
    - chmod +x ports/ci/mac-arm/build.sh
    - ./ports/ci/mac-arm/build.sh

  deploy_script:
    - chmod +x ports/ci/mac-arm/deploy.sh
    - ./ports/ci/mac-arm/deploy.sh
  
  binaries_artifacts:
    path: "webcamoid-packages/mac/*"

# build_task:
#   env:
#     COMPILER: clang
#     NJOBS: 4

#   freebsd_instance:
#     matrix:
#       image_family: freebsd-13-0-snap
#       image_family: freebsd-12-2
#     cpu: 2
#     memory: 4G

#   timeout_in: 60m

#   install_script:
#     - chmod +x ports/ci/cirrus/install_deps.sh
#     - ./ports/ci/cirrus/install_deps.sh

#   script:
#     - chmod +x ports/ci/cirrus/build.sh
#     - ./ports/ci/cirrus/build.sh

#   deploy_script:
#     - chmod +x ports/ci/cirrus/deploy.sh
#     - ./ports/ci/cirrus/deploy.sh
